#!/usr/bin/env python3
"""
RoamCore catalog auto-pipeline.

Reads every ``connections/<slug>/connection.yml`` and produces:

* ``docs/catalog/<category>/<slug>.md`` — one user-facing Markdown page
  per connection (catalog/category/slug.md), matching the
  ``docs/catalog/_templates/integration-page.template.md`` shape.
* ``docs/catalog/_inventory.yml`` — machine-readable catalog inventory
  with all non-excluded connections.
* ``connections/_all_connections_inventory.yml`` — full developer
  reference (includes excluded slices).
* ``docs/catalog/index.md`` — auto-regenerated landing page grouped by
  category.
* ``docs/catalog/<category>/index.md`` — per-category landing page.

Excluded slices (see ``docs/catalog/_exclude.yml``) are kept in the
developer inventory but skipped from the user-facing catalog. Entries
that look like they need a human pass are surfaced with a
``[NEEDS-CURATION-REVIEW]`` banner so Bernard can edit later.

Usage::

    python3 scripts/build_catalog.py                # build from on-disk YAMLs
    python3 scripts/build_catalog.py --connections <dir>
    python3 scripts/build_catalog.py --check        # dry-run + verify

The script uses only the Python stdlib + PyYAML (already vendored in
``.venv``). It does NOT modify any ``connection.yml``.
"""

from __future__ import annotations

import argparse
import io
import sys
from collections import defaultdict
from pathlib import Path
from typing import Iterable

# Make ``scripts/`` importable when invoked directly.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import build_catalog_lib as lib  # noqa: E402


CATALOG_DIR = ROOT / "docs" / "catalog"
TEMPLATE_PATH = CATALOG_DIR / "_templates" / "integration-page.template.md"
INVENTORY_PATH = CATALOG_DIR / "_inventory.yml"
EXCLUDE_PATH = CATALOG_DIR / "_exclude.yml"
INDEX_PATH = CATALOG_DIR / "index.md"
CONNECTIONS_DIR = ROOT / "connections"
ALL_INVENTORY_PATH = ROOT / "connections" / "_all_connections_inventory.yml"


# ---------------------------------------------------------------------------
# Exclude file I/O
# ---------------------------------------------------------------------------


def read_exclude(path: Path) -> list[str]:
    """Load the exclude list, falling back to the lib default."""

    if not path.exists():
        return list(lib.DEFAULT_EXCLUDE)

    text = path.read_text(encoding="utf-8")
    excludes = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        excludes.append(line)
    return excludes or list(lib.DEFAULT_EXCLUDE)


def write_exclude(path: Path, excludes: list[str]) -> None:
    """(Re-)write the exclude file."""

    body = (
        "# Slices excluded from the user-facing catalog.\n"
        "#\n"
        "# These are real RoamCore features but they target operators /\n"
        "# developers / agent authors — not van owners browsing the\n"
        "# catalog. They still appear in:\n"
        "#   connections/_all_connections_inventory.yml\n"
        "# for developer reference.\n"
        "#\n"
        "# One slug per line.\n\n"
    )
    body += "\n".join(excludes) + "\n"
    path.write_text(body, encoding="utf-8")


# ---------------------------------------------------------------------------
# Inventory YAML emission (stdlib only — no PyYAML emit dependency)
# ---------------------------------------------------------------------------


def _yaml_escape(value: str) -> str:
    """Naive but safe scalar quoting for the YAML we emit."""

    needs_quote = any(ch in value for ch in [":", "#", "[", "]", "{", "}", "&", "*", "!", "|", ">", "'", '"', "%", "@", "`"])
    if needs_quote or value != value.strip() or value == "":
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def emit_inventory(items: list[dict[str, object]], full: bool = False) -> str:
    """Emit a hand-rolled, perfectly-readable YAML inventory.

    Doing this by hand (instead of via PyYAML) lets us guarantee the
    output stays stable, sorted, and human-diffable.
    """

    out = io.StringIO()
    out.write("# RoamCore catalog inventory (auto-generated by scripts/build_catalog.py)\n")
    out.write("# DO NOT EDIT BY HAND — regenerate with:\n")
    out.write("#   python3 scripts/build_catalog.py\n")
    out.write("\n")
    if full:
        out.write("# Full developer inventory (includes operator-internal slices).\n")
        out.write("inventory_full: true\n")
    else:
        out.write("# User-facing inventory (excludes operator-internal slices — see _exclude.yml).\n")
        out.write("inventory_full: false\n")
    out.write("\nitems:\n")
    for item in sorted(items, key=lambda x: (str(x.get("category", "z")), str(x.get("title", "")))):
        out.write(f"  - id: {_yaml_escape(str(item['id']))}\n")
        out.write(f"    title: {_yaml_escape(str(item['title']))}\n")
        out.write(f"    category: {_yaml_escape(str(item['category']))}\n")
        out.write(f"    yaml_category: {_yaml_escape(str(item['yaml_category']))}\n")
        out.write(f"    support_tier: {_yaml_escape(str(item['support_tier']))}\n")
        out.write(f"    install_method: {_yaml_escape(str(item['install_method']))}\n")
        out.write(f"    status: {_yaml_escape(str(item['status']))}\n")
        out.write(f"    page: catalog/{item['category']}/{item['slug']}.md\n")
        out.write(f"    summary: {_yaml_escape(str(item['summary']))}\n")
        if item.get("needs_curation_review"):
            out.write("    needs_curation_review: true\n")
        out.write("    tags:\n")
        for t in item["tags"]:  # type: ignore[index]
            out.write(f"      - {_yaml_escape(str(t))}\n")
    return out.getvalue()


def inventory_items_for(connections: list[lib.Connection]) -> list[dict[str, object]]:
    items = []
    for c in connections:
        items.append(
            {
                "id": c.raw_id or c.slug,
                "slug": c.slug,
                "title": c.title,
                "category": c.catalog_category,
                "yaml_category": c.yaml_category,
                "support_tier": c.tier,
                "install_method": c.install_method,
                "status": c.status,
                "summary": c.summary,
                "tags": c.tags,
                "needs_curation_review": c.needs_curation_review,
            }
        )
    return items


# ---------------------------------------------------------------------------
# Landing-page rendering
# ---------------------------------------------------------------------------


def render_catalog_index(
    user_facing: list[lib.Connection],
    catalog_dir: Path,
) -> str:
    """Render ``docs/catalog/index.md`` grouped by category.

    IKEA-style: plain English, plain bullet list, no tier letters,
    no install codes, no warning emojis.
    """

    by_cat: dict[str, list[lib.Connection]] = defaultdict(list)
    for c in user_facing:
        by_cat[c.catalog_category].append(c)

    out = io.StringIO()
    out.write("# Catalog\n\n")
    out.write(
        "Stuff you can add to your van. Pick what you want and install it.\n\n"
    )

    for cat in sorted(by_cat):
        out.write(f"## {cat.title()}\n\n")
        for c in sorted(by_cat[cat], key=lambda x: x.title):
            out.write(f"- **[{c.title}]({cat}/{c.slug}.md)** \u2014 {c.summary}\n")
        out.write("\n")
    return out.getvalue()


def render_category_index(conns: list[lib.Connection], category: str) -> str:
    """Render a per-category landing page (e.g. ``docs/catalog/comfort/index.md``).

    Plain bullet list. No tier letters.
    """

    out = io.StringIO()
    out.write(f"# {category.title()}\n\n")
    for c in sorted(conns, key=lambda x: x.title):
        out.write(f"- **[{c.title}]({c.slug}.md)** \u2014 {c.summary}\n")
    return out.getvalue()


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def build(connections_dir: Path = CONNECTIONS_DIR, *, check_only: bool = False) -> int:
    excludes = read_exclude(EXCLUDE_PATH)
    print(f"[build_catalog] excludes: {excludes}")

    all_conns, skipped = lib.discover_connections(connections_dir, excludes=excludes)
    print(f"[build_catalog] discovered {len(all_conns)} connection.yml files ({len(skipped)} skipped)")

    user_facing = [c for c in all_conns if not c.excluded]
    excluded = [c for c in all_conns if c.excluded]
    print(f"[build_catalog] user-facing: {len(user_facing)}, excluded: {len(excluded)}")

    if check_only:
        # In check mode, just verify inventory would be non-empty and well-formed.
        if not user_facing:
            print("[build_catalog] ERROR: no user-facing connections discovered", file=sys.stderr)
            return 1
        # Render the index in memory to confirm no template errors
        render_catalog_index(user_facing, CATALOG_DIR)
        for c in user_facing:
            lib.render_page(c)
        print(f"[build_catalog] --check OK ({len(user_facing)} user-facing entries)")
        return 0

    # Ensure exclude file exists (write defaults if missing)
    if not EXCLUDE_PATH.exists():
        print(f"[build_catalog] writing default {EXCLUDE_PATH}")
        write_exclude(EXCLUDE_PATH, lib.DEFAULT_EXCLUDE)

    # Clean previous auto-generated pages + category indexes (preserves other files)
    _purge_auto_generated(CATALOG_DIR)

    # Render per-connection pages
    CATALOG_DIR.mkdir(parents=True, exist_ok=True)
    generated_files = []
    for c in user_facing:
        cat_dir = CATALOG_DIR / c.catalog_category
        cat_dir.mkdir(parents=True, exist_ok=True)
        page_path = cat_dir / f"{c.slug}.md"
        page_path.write_text(lib.render_page(c), encoding="utf-8")
        generated_files.append(str(page_path.relative_to(CATALOG_DIR)))

    # Render per-category landing pages
    by_cat: dict[str, list[lib.Connection]] = defaultdict(list)
    for c in user_facing:
        by_cat[c.catalog_category].append(c)
    for cat, items in by_cat.items():
        cat_dir = CATALOG_DIR / cat
        cat_dir.mkdir(parents=True, exist_ok=True)
        idx_path = cat_dir / "index.md"
        idx_path.write_text(render_category_index(items, cat), encoding="utf-8")
        generated_files.append(str(idx_path.relative_to(CATALOG_DIR)))

    # Render top-level catalog index
    INDEX_PATH.write_text(render_catalog_index(user_facing, CATALOG_DIR), encoding="utf-8")
    generated_files.append(str(INDEX_PATH.relative_to(CATALOG_DIR)))

    # Emit inventories
    INVENTORY_PATH.write_text(
        emit_inventory(inventory_items_for(user_facing), full=False),
        encoding="utf-8",
    )
    generated_files.append(str(INVENTORY_PATH.relative_to(CATALOG_DIR)))

    ALL_INVENTORY_PATH.parent.mkdir(parents=True, exist_ok=True)
    ALL_INVENTORY_PATH.write_text(
        emit_inventory(inventory_items_for(all_conns), full=True),
        encoding="utf-8",
    )

    # Write the manifest so next run's _purge_auto_generated can clean up
    # ONLY the files we generated (legacy stubs are preserved).
    (CATALOG_DIR / ".build_catalog_manifest.txt").write_text(
        "\n".join(sorted(generated_files)) + "\n",
        encoding="utf-8",
    )

    print(f"[build_catalog] wrote {len(user_facing)} catalog pages under {CATALOG_DIR}")
    print(f"[build_catalog] wrote {INDEX_PATH}")
    print(f"[build_catalog] wrote {INVENTORY_PATH}")
    print(f"[build_catalog] wrote {ALL_INVENTORY_PATH}")
    if skipped:
        print(f"[build_catalog] ! skipped {len(skipped)} unparseable files: {[s for s, _ in skipped]}")
    return 0


def _purge_auto_generated(catalog_dir: Path) -> None:
    """Remove only the files we generated in our last run.

    Tracks generated files via ``.build_catalog_manifest.txt`` at the
    catalog root. Anything not in the manifest is preserved (legacy
    stubs, hand-edited files, category indexes that don't match our
    slug pattern, etc.).
    """

    manifest = catalog_dir / ".build_catalog_manifest.txt"
    if not manifest.exists():
        return
    if not catalog_dir.exists():
        return
    for line in manifest.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        path = catalog_dir / line
        if path.exists():
            path.unlink()
    manifest.unlink()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the RoamCore catalog from connection.yml files.")
    parser.add_argument(
        "--connections",
        type=Path,
        default=CONNECTIONS_DIR,
        help="Path to the connections/ directory (default: ./connections)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Dry-run: parse everything but don't write any files.",
    )
    args = parser.parse_args(argv)

    return build(args.connections, check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())